services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: Shopping.Api
      dockerfile: Dockerfile

  shopping.client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: Shopping.Client
      dockerfile: Dockerfile

  shopping.db:
    image: mongo